name: 'Set GitHub Custom Metadata'
description: 'Sets custom metadata in the OP of a GitHub issue'
inputs:
  issue_number:
    description: 'The issue body to set a value in'
    required: false
  key:
    description: 'The key to set a value for'
    required: true
  value:
    description: 'The value to set'
    required: true
  myToken:  # id of input
    description: 'The token for access'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
